name: Java CI with Maven

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events to the 'main' branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # The type of machine to run on
    runs-on: ubuntu-latest

    # setup the MySQL database in the local environment to pass tests
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: users
        ports: 
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval=10s --health-timeout=5s
        
    # Now we execute the steps to run the project
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./app/peer-assessment-backend

    - name: Run Tests
      run: mvn test
      working-directory: ./app/peer-assessment-backend
