name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: front
        run: npm install

      - name: Run tests
        working-directory: front
        run: npm run test -- --watchAll=false

      - name: Verify App.tsx loads
        working-directory: front
        run: npm run test -- --testPathPattern=src/App.test.tsx

      - name: Run the build
        working-directory: front
        run: npm run build
