name: CI

on:
  push:
    branches:
      - main
      - 'refs/tags/*'
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version

      - name: Install dependencies
        run: |
          cd front
          npm install

      - name: Run tests
        run: |
          cd front
          npm test # Adjust this if you have a specific test command

      - name: Build
        run: |
          cd front
          npm run build
